name: place-extraction
channels:
- conda-forge
- defaults
dependencies:
- python=3.7
- jupyter
- ipykernel
- matplotlib=3.1.0
- pandas=0.24.2
- geopandas=0.5.0
- geopy=1.20.0
- flake8
- spacy
- plotly=3.10.0
- dash=0.43.0
- pyshp=2.1.0
- beautifulsoup4=4.7.1
