name: place-extraction
channels:
- conda-forge
- defaults
- lcvriend
dependencies:
- python=3.7
# jupyter
- jupyter
- ipykernel
- jupyterlab
# data
- pandas=>0.24.2
- tabulate
# visualization
- matplotlib=>3.1.0
- altair
- folium
- adjusttext
# geographical packages
- geopandas=>0.5.0
- descartes=>1.1.0
- geopy=>1.20.0
- fiona=>1.8.6
- pyshp=>2.1.0
# nlp
- spacy
# utils
- flake8 # maybe
- tqdm
- lxml
- beautifulsoup4=>4.7.1
- humannotator
